version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  java:
    docker:
      - image: circleci/openjdk:8-jdk-node

jobs:

  build:
    description: |
      Checkout, build, test, and upload test results
    executor: java
    steps:
      - checkout
      - run: make import-keys
      - restore_cache:
          key: almaraz-{{ checksum "pom.xml" }}
      - run: make build
      - save_cache:
          paths:
            - ~/.m2
          key: almaraz-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  build:
    jobs:
      - build
