version: 2.1
orbs:
  maven: circleci/maven@0.0.8
workflows:
  build:
    jobs:
      - run:
          command: |
            echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
            echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
      - maven/test:
          settings_file: .circleci/settings.xml
