version: 2.1

executors:
  java:
    docker:
      - image: circleci/openjdk:8-jdk-node

jobs:
  build:
    description: |
      Checkout, build, test, and upload test results
    executor: java
    steps:
      - checkout
      - run:
          command: |
            echo $GPG_SECRET_KEYS | $GPG_EXECUTABLE --import
            echo $GPG_OWNERTRUST | $GPG_EXECUTABLE --import-ownertrust
      - restore_cache:
          key: almaraz-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline --settings .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: almaraz-{{ checksum "pom.xml" }}
      - run: mvn install --settings .circleci/settings.xml
      - store_test_results:
          path: target/surefire-reports

workflows:
  build:
    jobs:
      - build
